# Generated by Django 4.0.5 on 2022-06-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemaitem',
            old_name='user',
            new_name='username',
        ),
    ]
