# Generated by Django 4.0.4 on 2022-05-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='Images/None/noimg.png', upload_to='Images/'),
        ),
    ]
